/* parser generated by jison 0.4.13 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var CQPParser = (function(){
var parser = {trace: function trace() { },
yy: {},
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
symbols_: {"error":2,"expressions":3,"tokens":4,"EOF":5,"token":6,"EMPTY":7,"[":8,"and_block":9,"]":10,"repeat":11,"{":12,"INT":13,",":14,"}":15,"or_block":16,"bound_block":17,"&":18,"bound":19,"or":20,"|":21,"bool":22,"TYPE":23,"infix_op":24,"VALUE":25,"FLAG":26,"DATE_FROM":27,"DATE_OP":28,"DATE_VAL":29,"DATE_TO":30,"FUNC":31,"FUNCVAL":32,"=":33,"!=":34,"contains":35,"not":36,"^=":37,"&=":38,"*=":39,"!*=":40,"_=":41,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"EMPTY",8:"[",10:"]",12:"{",13:"INT",14:",",15:"}",18:"&",21:"|",23:"TYPE",25:"VALUE",26:"FLAG",27:"DATE_FROM",28:"DATE_OP",29:"DATE_VAL",30:"DATE_TO",31:"FUNC",32:"FUNCVAL",33:"=",34:"!=",35:"contains",36:"not",37:"^=",38:"&=",39:"*=",40:"!*=",41:"_="},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[6,3],[6,2],[11,5],[11,4],[9,1],[9,1],[9,3],[17,1],[17,3],[16,1],[16,3],[22,1],[22,1],[20,3],[20,2],[20,7],[19,2],[24,1],[24,1],[24,1],[24,2],[24,1],[24,1],[24,1],[24,1],[24,1]],
=======
symbols_: {"error":2,"expressions":3,"tokens":4,"EOF":5,"token":6,"EMPTY":7,"[":8,"and_block":9,"]":10,"repeat":11,"{":12,"INT":13,",":14,"}":15,"or_block":16,"bound_block":17,"&":18,"bound":19,"or":20,"|":21,"date_time_expr":22,"bool":23,"TYPE":24,"infix_op":25,"VALUE":26,"FLAG":27,"date":28,"DATE_TIME_KEY":29,"DATE_OP":30,"DATE_VAL":31,"FUNC":32,"FUNCVAL":33,"=":34,"!=":35,"contains":36,"not":37,"^=":38,"&=":39,"*=":40,"_=":41,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"EMPTY",8:"[",10:"]",12:"{",13:"INT",14:",",15:"}",18:"&",21:"|",24:"TYPE",26:"VALUE",27:"FLAG",29:"DATE_TIME_KEY",30:"DATE_OP",31:"DATE_VAL",32:"FUNC",33:"FUNCVAL",34:"=",35:"!=",36:"contains",37:"not",38:"^=",39:"&=",40:"*=",41:"_="},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[6,3],[6,2],[11,5],[11,4],[9,1],[9,1],[9,3],[17,1],[17,3],[16,1],[16,3],[16,1],[23,1],[23,1],[20,3],[20,2],[22,1],[22,3],[28,3],[19,2],[25,1],[25,1],[25,1],[25,2],[25,1],[25,1],[25,1],[25,1]],
>>>>>>> ambiguos grammar with ampersand, will try paren approach
=======
symbols_: {"error":2,"expressions":3,"tokens":4,"EOF":5,"token":6,"EMPTY":7,"[":8,"and_block":9,"]":10,"repeat":11,"{":12,"INT":13,",":14,"}":15,"or_block":16,"bound_block":17,"&":18,"bound":19,"or":20,"(":21,"|":22,")":23,"bool":24,"TYPE":25,"infix_op":26,"VALUE":27,"FLAG":28,"date_time_expr":29,"date":30,"date_key":31,"DATE_OP":32,"DATE_VAL":33,"int":34,"FUNC":35,"FUNCVAL":36,"=":37,"!=":38,"contains":39,"not":40,"^=":41,"&=":42,"*=":43,"_=":44,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"EMPTY",8:"[",10:"]",12:"{",13:"INT",14:",",15:"}",18:"&",21:"(",22:"|",23:")",25:"TYPE",27:"VALUE",28:"FLAG",32:"DATE_OP",33:"DATE_VAL",34:"int",35:"FUNC",36:"FUNCVAL",37:"=",38:"!=",39:"contains",40:"not",41:"^=",42:"&=",43:"*=",44:"_="},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[6,3],[6,2],[11,5],[11,4],[9,1],[9,1],[9,3],[17,1],[17,3],[16,1],[16,5],[24,1],[24,1],[20,3],[20,2],[29,1],[29,3],[30,3],[31,4],[19,2],[26,1],[26,1],[26,1],[26,2],[26,1],[26,1],[26,1],[26,1]],
>>>>>>> cqp parser rewrite in progress
=======
symbols_: {"error":2,"expressions":3,"tokens":4,"EOF":5,"token":6,"EMPTY":7,"[":8,"and_block":9,"]":10,"repeat":11,"{":12,"INT":13,",":14,"}":15,"or_block":16,"bound_block":17,"&":18,"bound":19,"or":20,"date_time_expr[dte]":21,"|":22,"(":23,")":24,"bool":25,"TYPE":26,"infix_op":27,"VALUE":28,"FLAG":29,"date_time_expr":30,"date":31,"date_time_expr[dte1]":32,"date_time_expr[dte2]":33,"int":34,"date_op":35,"DATE_TIME_VAL":36,"FUNC":37,"FUNCVAL":38,"DATE_OP":39,"=":40,"INFIX_OP":41,"contains":42,"not":43,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"EMPTY",8:"[",10:"]",12:"{",13:"INT",14:",",15:"}",18:"&",21:"date_time_expr[dte]",22:"|",23:"(",24:")",26:"TYPE",28:"VALUE",29:"FLAG",32:"date_time_expr[dte1]",33:"date_time_expr[dte2]",34:"int",36:"DATE_TIME_VAL",37:"FUNC",38:"FUNCVAL",39:"DATE_OP",40:"=",41:"INFIX_OP",42:"contains",43:"not"},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[6,3],[6,2],[11,5],[11,4],[9,1],[9,1],[9,3],[17,1],[17,3],[16,1],[16,1],[16,3],[16,3],[25,1],[25,1],[20,3],[20,2],[30,1],[30,5],[31,6],[19,2],[35,1],[35,1],[27,1],[27,1],[27,1],[27,2]],
>>>>>>> before major parser overhaul
=======
symbols_: {"error":2,"expressions":3,"tokens":4,"EOF":5,"token":6,"EMPTY":7,"[":8,"expr1":9,"token_repetition0":10,"]":11,"repeat":12,"{":13,"INT":14,",":15,"}":16,"and_block":17,"or_block":18,"bound_block":19,"&":20,"bound":21,"or":22,"date_time_expr[dte]":23,"|":24,"(":25,")":26,"bool":27,"TYPE":28,"infix_op":29,"VALUE":30,"FLAG":31,"date_time_expr":32,"date":33,"date_time_expr[dte1]":34,"date_time_expr[dte2]":35,"int":36,"date_op":37,"DATE_TIME_VAL":38,"expr0":39,"FUNC":40,"FUNCVAL":41,"DATE_OP":42,"=":43,"INFIX_OP":44,"contains":45,"not":46,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"EMPTY",8:"[",11:"]",13:"{",14:"INT",15:",",16:"}",20:"&",23:"date_time_expr[dte]",24:"|",25:"(",26:")",28:"TYPE",30:"VALUE",31:"FLAG",34:"date_time_expr[dte1]",35:"date_time_expr[dte2]",36:"int",38:"DATE_TIME_VAL",40:"FUNC",41:"FUNCVAL",42:"DATE_OP",43:"=",44:"INFIX_OP",45:"contains",46:"not"},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[6,4],[12,5],[12,4],[17,1],[17,1],[17,3],[19,1],[19,3],[18,1],[18,1],[18,3],[18,3],[27,1],[27,1],[22,3],[22,2],[32,1],[32,5],[33,6],[39,1],[39,1],[39,3],[9,1],[9,3],[21,2],[37,1],[37,1],[29,1],[29,1],[29,1],[29,2],[10,0],[10,3]],
>>>>>>> finished parser rewrite, time for graphical stuff
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: typeof console !== 'undefined' ? console.log(JSON.stringify($$[$0-1], null, 4)) : print($$[$0-1]);
          return $$[$0-1]; 
break;
case 2:this.$ = [$$[$0]]
break;
case 3:this.$ = [].concat([$$[$0-1]], $$[$0])
break;
case 4:this.$ = {"and_block":[[{type:"word",op:"=",val:""}]]}
break;
case 5:this.$ = $$[$0-2]
break;
case 6:this.$ =  [Number($$[$0-3]), Number($$[$0-1])]
break;
case 7:this.$ = [Number($$[$0-2])]
break;
case 8:this.$ = {"and_block" : [$$[$0]]}
break;
case 9:this.$ = {"bound" : $$[$0], "and_block" : []}
break;
case 10:$$[$0].and_block.push($$[$0-2]); this.$ = $$[$0];
break;
case 11:this.$ = {}; this.$[$$[$0]] = true
break;
case 12:this.$ = $$[$0]; $$[$0][$$[$0-2]] = true
break;
case 13:this.$ = [$$[$0]]
break;
case 14:
            for(key in $$[$0]) {
                if($$[$0][key].length > 1)
                    $$[$0][key] = $$[$0][key].filter(function(item) {
                        return item[0] == "=";
                    }); 
                $$[$0][key] = $$[$0][key][0][1]// only one item left, return value
            }
            var val = [$$[$0]["_.fromdate"], $$[$0]["_.todate"], $$[$0]["_.fromtime"], $$[$0]["_.totime"]].join(",");
            this.$ = [{type : "date_interval", op : "=", val: val}]
        
break;
case 15:this.$ = [].concat([$$[$0-2]], $$[$0])
break;
case 16:this.$ = $$[$0-1]
break;
case 17:this.$ = $$[$0]
break;
case 18:this.$ = $$[$0]
break;
case 19:this.$ =  {type : $$[$0-2], op : $$[$0-1], val: $$[$0].slice(1, -1)}
break;
case 20:
            var chars = $$[$0].slice(1).split("");
            $$[$0-1].flags = {};
            for(var i = 0; i < chars.length; i++)
                $$[$0-1].flags[chars[i]] = true;
                
            this.$ = $$[$0-1];
        
break;
case 21:
            this.$ = $$[$0];
        
break;
case 22:
            this.$ = _.merge({}, $$[$0-3], $$[$0-1], function(a, b) {
              return _.isArray(a) ? a.concat(b) : undefined;
            });
        
break;
case 23:
            // console.log("DATE_TIME_VAL", $$[$0])
            if(!_.isPlainObject(this.$)) this.$ = {}
            

            if(typeof this.$[$$[$0-3]] == "undefined") this.$[$$[$0-3]] = []

            // if($$[$0-1] == "=")
            this.$[$$[$0-3]].push([$$[$0-1], $$[$0]])

        
break;
case 26:this.$ = $$[$0-1]
break;
case 27:
            // if(!_.isArray($$[$0]))
            //     // this.$ = [(_.values($$[$0])[0])]
            //     this.$ = [($$[$0])]
            // else
            this.$ = $$[$0]
        
break;
case 28:  
            c.log("has child", !!$$[$0-2].child)

            if($$[$0-1] == "|")
                this.$ = [$$[$0-2]]

            // if(typeof $$[$0-2].parent == "undefined") 
            //     $$[$0-2].parent = []
            // if(typeof $$[$0-2].sibling == "undefined") 
            //     $$[$0-2].sibling = []

            // if($$[$0-1] == "&")
            //     $$[$0-2].parent.push($$[$0])
            // else if($$[$0-1] == "|")
            //     $$[$0-2].sibling.push($$[$0])
            // $$[$0].bool = $$[$0-1]
            // $$[$0-2].child = $$[$0];

            return;
            var isTerminal = !_.isArray($$[$0])

            function stripKey(item) {
                if("or" in item || "date" in item)
                    return _.values(item)[0]
                else 
                    return item
            }
            // this.$ = output.map(stripKey);

            // isTerminal

            if($$[$0-1] == "&")
                c.log("expr", $$[$0-2], $$[$0], isTerminal)

            output = [].concat($$[$0-2], $$[$0])
            this.$ = output

            // c.log("expr", $$[$0-2], $$[$0-1], $$[$0] )
            // c.log("expr", isTerminal, $$[$0] )
            // var output = []
            if(_.isArray($$[$0]))
                output = [].concat($$[$0-2], $$[$0])
            else {
                $$[$0-2].push($$[$0])
                output = $$[$0-2]
            }
            

            // c.log("expr0", $$[$0-2])
            this.$ = output
            // if("date" in $$[$0]) {
                
            // }
        
break;
case 29: this.$ = $$[$0-1]
break;
case 30:this.$ = $$[$0]
break;
case 31:this.$ = "="
break;
case 32:this.$ = "="
break;
case 33:this.$ = $$[$0]
break;
case 34:this.$ = "contains"
break;
<<<<<<< HEAD
<<<<<<< HEAD
case 30:this.$ = "&="
break;
case 31:this.$ = "*="
break;
<<<<<<< HEAD
case 29:this.$ = "!*="
break;
case 30:this.$ = "_="
break;
}
},
table: [{3:1,4:2,6:3,7:[1,4],8:[1,5]},{1:[3]},{5:[1,6]},{4:7,5:[2,2],6:3,7:[1,4],8:[1,5],11:8,12:[1,9]},{5:[2,4],7:[2,4],8:[2,4],12:[2,4]},{9:10,16:11,17:12,19:14,20:13,23:[1,15],27:[1,16],31:[1,17]},{1:[2,1]},{5:[2,3]},{5:[2,6],7:[2,6],8:[2,6],12:[2,6]},{13:[1,18]},{10:[1,19]},{10:[2,9],18:[1,20]},{10:[2,10]},{10:[2,14],18:[2,14],21:[1,21],26:[1,22]},{10:[2,12],18:[1,23]},{24:24,33:[1,25],34:[1,26],35:[1,27],36:[1,28],37:[1,29],38:[1,30],39:[1,31],40:[1,32],41:[1,33]},{28:[1,34]},{32:[1,35]},{14:[1,36]},{5:[2,5],7:[2,5],8:[2,5],12:[2,5]},{9:37,16:11,17:12,19:14,20:13,23:[1,15],27:[1,16],31:[1,17]},{16:38,20:13,23:[1,15],27:[1,16]},{10:[2,19],18:[2,19],21:[2,19],26:[2,19]},{17:39,19:14,31:[1,17]},{25:[1,40]},{25:[2,22]},{25:[2,23]},{25:[2,24]},{35:[1,41]},{25:[2,26]},{25:[2,27]},{25:[2,28]},{25:[2,29]},{25:[2,30]},{29:[1,42]},{10:[2,21],18:[2,21]},{13:[1,43],15:[1,44]},{10:[2,11]},{10:[2,15],18:[2,15]},{10:[2,13]},{10:[2,18],18:[2,18],21:[2,18],26:[2,18]},{25:[2,25]},{18:[1,46],21:[1,47],22:45},{15:[1,48]},{5:[2,8],7:[2,8],8:[2,8],12:[2,8]},{30:[1,49]},{30:[2,16]},{30:[2,17]},{5:[2,7],7:[2,7],8:[2,7],12:[2,7]},{28:[1,50]},{29:[1,51]},{10:[2,20],18:[2,20],21:[2,20],26:[2,20]}],
defaultActions: {6:[2,1],7:[2,3],12:[2,10],25:[2,22],26:[2,23],27:[2,24],29:[2,26],30:[2,27],31:[2,28],32:[2,29],33:[2,30],37:[2,11],39:[2,13],41:[2,25],46:[2,16],47:[2,17]},
=======
case 32:this.$ = "_="
break;
}
},
<<<<<<< HEAD
table: [{3:1,4:2,6:3,7:[1,4],8:[1,5]},{1:[3]},{5:[1,6]},{4:7,5:[2,2],6:3,7:[1,4],8:[1,5],11:8,12:[1,9]},{5:[2,4],7:[2,4],8:[2,4],12:[2,4]},{9:10,16:11,17:12,19:15,20:13,22:14,24:[1,16],28:17,29:[1,19],32:[1,18]},{1:[2,1]},{5:[2,3]},{5:[2,6],7:[2,6],8:[2,6],12:[2,6]},{13:[1,20]},{10:[1,21]},{10:[2,9],18:[1,22]},{10:[2,10]},{10:[2,14],18:[2,14],21:[1,23],27:[1,24]},{10:[2,16],18:[2,16]},{10:[2,12],18:[1,25]},{25:26,34:[1,27],35:[1,28],36:[1,29],37:[1,30],38:[1,31],39:[1,32],40:[1,33],41:[1,34]},{10:[2,21],18:[1,37],21:[1,36],23:35},{33:[1,38]},{30:[1,39]},{14:[1,40]},{5:[2,5],7:[2,5],8:[2,5],12:[2,5]},{9:41,16:11,17:12,19:15,20:13,22:14,24:[1,16],28:17,29:[1,19],32:[1,18]},{16:42,20:13,22:14,24:[1,16],28:17,29:[1,19]},{10:[2,20],18:[2,20],21:[2,20],27:[2,20]},{17:43,19:15,32:[1,18]},{26:[1,44]},{26:[2,25]},{26:[2,26]},{26:[2,27]},{36:[1,45]},{26:[2,29]},{26:[2,30]},{26:[2,31]},{26:[2,32]},{22:46,28:17,29:[1,19]},{29:[2,17]},{29:[2,18]},{10:[2,24],18:[2,24]},{31:[1,47]},{13:[1,48],15:[1,49]},{10:[2,11]},{10:[2,15],18:[2,15]},{10:[2,13]},{10:[2,19],18:[2,19],21:[2,19],27:[2,19]},{26:[2,28]},{10:[2,22],18:[2,22]},{10:[2,23],18:[2,23],21:[2,23]},{15:[1,50]},{5:[2,8],7:[2,8],8:[2,8],12:[2,8]},{5:[2,7],7:[2,7],8:[2,7],12:[2,7]}],
defaultActions: {6:[2,1],7:[2,3],12:[2,10],27:[2,25],28:[2,26],29:[2,27],31:[2,29],32:[2,30],33:[2,31],34:[2,32],36:[2,17],37:[2,18],41:[2,11],43:[2,13],45:[2,28]},
>>>>>>> ambiguos grammar with ampersand, will try paren approach
=======
table: [{3:1,4:2,6:3,7:[1,4],8:[1,5]},{1:[3]},{5:[1,6]},{4:7,5:[2,2],6:3,7:[1,4],8:[1,5],11:8,12:[1,9]},{5:[2,4],7:[2,4],8:[2,4],12:[2,4]},{9:10,16:11,17:12,19:15,20:13,21:[1,14],25:[1,16],35:[1,17]},{1:[2,1]},{5:[2,3]},{5:[2,6],7:[2,6],8:[2,6],12:[2,6]},{13:[1,18]},{10:[1,19]},{10:[2,9],18:[1,20]},{10:[2,10]},{10:[2,14],18:[2,14],23:[2,14],28:[1,21]},{20:22,25:[1,16]},{10:[2,12],18:[1,23]},{26:24,37:[1,25],38:[1,26],39:[1,27],40:[1,28],41:[1,29],42:[1,30],43:[1,31],44:[1,32]},{36:[1,33]},{14:[1,34]},{5:[2,5],7:[2,5],8:[2,5],12:[2,5]},{9:35,16:11,17:12,19:15,20:13,21:[1,14],25:[1,16],35:[1,17]},{10:[2,19],18:[2,19],22:[2,19],23:[2,19],28:[2,19]},{22:[1,36],28:[1,21]},{17:37,19:15,35:[1,17]},{27:[1,38]},{27:[2,25]},{27:[2,26]},{27:[2,27]},{39:[1,39]},{27:[2,29]},{27:[2,30]},{27:[2,31]},{27:[2,32]},{10:[2,24],18:[2,24]},{13:[1,40],15:[1,41]},{10:[2,11]},{16:42,20:13,21:[1,14],25:[1,16]},{10:[2,13]},{10:[2,18],18:[2,18],22:[2,18],23:[2,18],28:[2,18]},{27:[2,28]},{15:[1,43]},{5:[2,8],7:[2,8],8:[2,8],12:[2,8]},{23:[1,44]},{5:[2,7],7:[2,7],8:[2,7],12:[2,7]},{10:[2,15],18:[2,15],23:[2,15]}],
defaultActions: {6:[2,1],7:[2,3],12:[2,10],25:[2,25],26:[2,26],27:[2,27],29:[2,29],30:[2,30],31:[2,31],32:[2,32],35:[2,11],37:[2,13],39:[2,28]},
>>>>>>> cqp parser rewrite in progress
=======
case 31:this.$ = "not contains"
break;
}
},
table: [{3:1,4:2,6:3,7:[1,4],8:[1,5]},{1:[3]},{5:[1,6]},{4:7,5:[2,2],6:3,7:[1,4],8:[1,5],11:8,12:[1,9]},{5:[2,4],7:[2,4],8:[2,4],12:[2,4]},{9:10,16:11,17:12,19:16,20:13,23:[1,15],26:[1,17],30:14,31:18,34:[1,20],37:[1,19]},{1:[2,1]},{5:[2,3]},{5:[2,6],7:[2,6],8:[2,6],12:[2,6]},{13:[1,21]},{10:[1,22]},{10:[2,9],18:[1,23]},{10:[2,10]},{10:[2,14],18:[2,14],22:[1,24],24:[2,14],29:[1,25]},{10:[2,15],18:[2,15],24:[2,15]},{16:26,20:13,23:[1,15],26:[1,17],30:27,31:18,34:[1,20]},{10:[2,12],18:[1,28]},{27:29,40:[1,30],41:[1,31],42:[1,32],43:[1,33]},{10:[2,22],18:[2,22],22:[2,22],24:[2,22]},{38:[1,34]},{23:[1,35]},{14:[1,36]},{5:[2,5],7:[2,5],8:[2,5],12:[2,5]},{9:37,16:11,17:12,19:16,20:13,23:[1,15],26:[1,17],30:14,31:18,34:[1,20],37:[1,19]},{16:38,20:13,23:[1,15],26:[1,17],30:14,31:18,34:[1,20]},{10:[2,21],18:[2,21],22:[2,21],24:[2,21],29:[2,21]},{24:[1,39]},{18:[1,41],22:[1,42],24:[2,15],25:40},{17:43,19:16,37:[1,19]},{28:[1,44]},{28:[2,28]},{28:[2,29]},{28:[2,30]},{42:[1,45]},{10:[2,25],18:[2,25]},{26:[1,46]},{13:[1,47],15:[1,48]},{10:[2,11]},{10:[2,16],18:[2,16],24:[2,16]},{10:[2,17],18:[2,17],24:[2,17]},{23:[1,50],30:49,31:18,34:[1,20]},{23:[2,18],34:[2,18]},{23:[2,19],34:[2,19]},{10:[2,13]},{10:[2,20],18:[2,20],22:[2,20],24:[2,20],29:[2,20]},{28:[2,31]},{24:[1,51]},{15:[1,52]},{5:[2,8],7:[2,8],8:[2,8],12:[2,8]},{24:[1,53]},{23:[1,50],30:54,31:18,34:[1,20]},{35:55,39:[1,56],40:[1,57]},{5:[2,7],7:[2,7],8:[2,7],12:[2,7]},{10:[2,23],18:[2,23],22:[2,23],24:[2,23]},{18:[1,41],22:[1,42],25:40},{36:[1,58]},{36:[2,26]},{36:[2,27]},{10:[2,24],18:[2,24],22:[2,24],24:[2,24]}],
defaultActions: {6:[2,1],7:[2,3],12:[2,10],30:[2,28],31:[2,29],32:[2,30],37:[2,11],43:[2,13],45:[2,31],56:[2,26],57:[2,27]},
>>>>>>> before major parser overhaul
=======
case 35:this.$ = "not contains"
break;
case 36:this.$ = [];
break;
case 37:$$[$0-2].push($$[$0-1]);
break;
}
},
table: [{3:1,4:2,6:3,7:[1,4],8:[1,5]},{1:[3]},{5:[1,6]},{4:7,5:[2,2],6:3,7:[1,4],8:[1,5]},{5:[2,4],7:[2,4],8:[2,4]},{9:8,22:11,25:[1,12],28:[1,14],33:10,36:[1,13],39:9},{1:[2,1]},{5:[2,3]},{10:15,11:[2,36],20:[1,17],24:[1,18],27:16},{11:[2,27],20:[2,27],24:[2,27],26:[2,27]},{11:[2,24],20:[2,24],24:[2,24],26:[2,24]},{11:[2,25],20:[2,25],24:[2,25],26:[2,25],31:[1,19]},{9:20,22:11,25:[1,12],28:[1,14],33:10,36:[1,13],39:9},{25:[1,21]},{29:22,43:[1,23],44:[1,24],45:[1,25],46:[1,26]},{11:[1,27],20:[1,28]},{22:11,25:[1,12],28:[1,14],33:10,36:[1,13],39:29},{25:[2,17],28:[2,17],36:[2,17]},{25:[2,18],28:[2,18],36:[2,18]},{11:[2,20],20:[2,20],24:[2,20],26:[2,20],31:[2,20]},{20:[1,17],24:[1,18],26:[1,30],27:16},{28:[1,31]},{30:[1,32]},{30:[2,32]},{30:[2,33]},{30:[2,34]},{45:[1,33]},{5:[2,5],7:[2,5],8:[2,5]},{9:34,22:11,25:[1,12],28:[1,14],33:10,36:[1,13],39:9},{11:[2,28],20:[2,28],24:[2,28],26:[2,28]},{11:[2,26],20:[2,26],24:[2,26],26:[2,26]},{26:[1,35]},{11:[2,19],20:[2,19],24:[2,19],26:[2,19],31:[2,19]},{30:[2,35]},{11:[2,37],20:[2,37],24:[1,18],27:16},{37:36,42:[1,37],43:[1,38]},{38:[1,39]},{38:[2,30]},{38:[2,31]},{11:[2,23],20:[2,23],24:[2,23],26:[2,23]}],
defaultActions: {6:[2,1],7:[2,3],23:[2,32],24:[2,33],25:[2,34],33:[2,35],37:[2,30],38:[2,31]},
>>>>>>> finished parser rewrite, time for graphical stuff
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    this.lexer.setInput(input);
    this.lexer.yy = this.yy;
    this.yy.lexer = this.lexer;
    this.yy.parser = this;
    if (typeof this.lexer.yylloc == 'undefined') {
        this.lexer.yylloc = {};
    }
    var yyloc = this.lexer.yylloc;
    lstack.push(yyloc);
    var ranges = this.lexer.options && this.lexer.options.ranges;
    if (typeof this.yy.parseError === 'function') {
        this.parseError = this.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    function lex() {
        var token;
        token = self.lexer.lex() || EOF;
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (this.lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + this.lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: this.lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: this.lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(this.lexer.yytext);
            lstack.push(this.lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = this.lexer.yyleng;
                yytext = this.lexer.yytext;
                yylineno = this.lexer.yylineno;
                yyloc = this.lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                this.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


if(typeof require != "undefined")
    var _ = require("../../components/lodash/lodash")._

var c = console;/* generated by jison-lex 0.2.1 */
var lexer = (function(){
var lexer = {

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input) {
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len - 1);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return "DATE_TIME_VAL"
break;
case 1:return "int"
break;
case 2:return "DATE_OP"
break;
case 3:return "DATE_OP"
break;
case 4:return "DATE_OP"
break;
case 5:return "DATE_OP"
break;
case 6:return 45
break;
case 7:return "FUNC"
break;
case 8:return "FUNC"
break;
case 9:return "FUNCVAL"
break;
case 10:return "("
break;
case 11:return ")"
break;
case 12:/* skip whitespace */
break;
case 13:return "FLAG"
break;
case 14:return 46
break;
case 15:return 44
break;
case 16:return 44
break;
case 17:return 44
break;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
case 19:return 41
break;
case 20:return 40
break;
case 21:return 39
break;
case 22:return 33
break;
case 23:return 23
break;
case 24:return 25
break;
case 25:return 7
break;
case 26:return 8
break;
case 27:return 10
break;
case 28:return 21
break;
case 29:return 18
break;
case 30:return 12
break;
case 31:return 15
break;
case 32:return "INT"
break;
case 33:return 14
break;
case 34:return "%"
break;
case 35:return 5
break;
}
},
rules: [/^(?:int\(_\.text_datefrom\))/,/^(?:int\(_\.text_dateto\))/,/^(?:\d{8})/,/^(?:<=)/,/^(?:>=)/,/^(?:<)/,/^(?:>)/,/^(?: contains )/,/^(?:lbound\b)/,/^(?:rbound\b)/,/^(?:sentence\b)/,/^(?:\()/,/^(?:\))/,/^(?:\s+)/,/^(?:%[cd]+)/,/^(?:not\b)/,/^(?:!=)/,/^(?:\^=)/,/^(?:&=)/,/^(?:_=)/,/^(?:!\*=)/,/^(?:\*=)/,/^(?:=)/,/^(?:(_.)?[A-Za-z_]+)/,/^(?:["'].*?['"])/,/^(?:\[\s*\])/,/^(?:\[)/,/^(?:\])/,/^(?:\|)/,/^(?:&)/,/^(?:\{)/,/^(?:\})/,/^(?:\d+)/,/^(?:,)/,/^(?:%)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35],"inclusive":true}}
=======
case 22:return 41
=======
case 14:return 44
>>>>>>> cqp parser rewrite in progress
=======
case 18:return 41
>>>>>>> before major parser overhaul
=======
case 18:return 44
>>>>>>> finished parser rewrite, time for graphical stuff
break;
case 19:return 44
break;
case 20:return 43
break;
case 21:return 28
break;
case 22:return 30
break;
case 23:return 7
break;
case 24:return 8
break;
case 25:return 11
break;
case 26:return 24
break;
case 27:return 20
break;
case 28:return 13
break;
case 29:return 16
break;
case 30:return "INT"
break;
case 31:return 15
break;
case 32:return "%"
break;
case 33:return 5
break;
}
},
<<<<<<< HEAD
<<<<<<< HEAD
rules: [/^(?:int\(_\.text_datefrom\))/,/^(?:int\(_\.text_dateto\))/,/^(?:int\(_\.text_timefrom\))/,/^(?:int\(_\.text_timeto\))/,/^(?:\d{6,8})/,/^(?:<=)/,/^(?:>=)/,/^(?:<)/,/^(?:>)/,/^(?:=)/,/^(?: contains )/,/^(?:lbound\b)/,/^(?:rbound\b)/,/^(?:sentence\b)/,/^(?:\()/,/^(?:\))/,/^(?:\s+)/,/^(?:%[cd]+)/,/^(?:not\b)/,/^(?:!=)/,/^(?:\^=)/,/^(?:&=)/,/^(?:_=)/,/^(?:\*=)/,/^(?:=)/,/^(?:(_.)?[A-Za-z_]+)/,/^(?:["'].*?['"])/,/^(?:\[\s*\])/,/^(?:\[)/,/^(?:\])/,/^(?:\|)/,/^(?:&)/,/^(?:\{)/,/^(?:\})/,/^(?:\d+)/,/^(?:,)/,/^(?:%)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37],"inclusive":true}}
>>>>>>> ambiguos grammar with ampersand, will try paren approach
=======
rules: [/^(?:\d{6,8})/,/^(?:int\b)/,/^(?: contains )/,/^(?:lbound\b)/,/^(?:rbound\b)/,/^(?:sentence\b)/,/^(?:\()/,/^(?:\))/,/^(?:\s+)/,/^(?:%[cd]+)/,/^(?:not\b)/,/^(?:!=)/,/^(?:\^=)/,/^(?:&=)/,/^(?:_=)/,/^(?:\*=)/,/^(?:=)/,/^(?:(_.)?[A-Za-z_]+)/,/^(?:["'].*?['"])/,/^(?:\[\s*\])/,/^(?:\[)/,/^(?:\])/,/^(?:\|)/,/^(?:&)/,/^(?:\{)/,/^(?:\})/,/^(?:\d+)/,/^(?:,)/,/^(?:%)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],"inclusive":true}}
>>>>>>> cqp parser rewrite in progress
=======
rules: [/^(?:\d{6,8})/,/^(?:int\b)/,/^(?:<=)/,/^(?:=>)/,/^(?:<)/,/^(?:>)/,/^(?: contains )/,/^(?:lbound\b)/,/^(?:rbound\b)/,/^(?:sentence\b)/,/^(?:\()/,/^(?:\))/,/^(?:\s+)/,/^(?:%[cd]+)/,/^(?:not\b)/,/^(?:!=)/,/^(?:\^=)/,/^(?:&=)/,/^(?:_=)/,/^(?:\*=)/,/^(?:=)/,/^(?:(_.)?[A-Za-z_]+)/,/^(?:["'].*?['"])/,/^(?:\[\s*\])/,/^(?:\[)/,/^(?:\])/,/^(?:\|)/,/^(?:&)/,/^(?:\{)/,/^(?:\})/,/^(?:\d+)/,/^(?:,)/,/^(?:%)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33],"inclusive":true}}
>>>>>>> before major parser overhaul
};
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = CQPParser;
exports.Parser = CQPParser.Parser;
exports.parse = function () { return CQPParser.parse.apply(CQPParser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}